### ISSUE TITLE
Debian 11 or 12 error install script

### ISSUE THREAD

**Issue by aasolyar** [admitrievsky/freeroute#5]
Adding sudoers file
Traceback (most recent call last):
  File "/vpn/freeroute/service/installer.py", line 289, in <module>
    main()
  File "/vpn/freeroute/service/installer.py", line 279, in main
    init_sudoers(get_user())
  File "/vpn/freeroute/service/installer.py", line 196, in init_sudoers
    with open('/etc/sudoers.d/freeroute', 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/etc/sudoers.d/freeroute'

**Comment by aasolyar** [comment]
Solution - before run script need to create folder "sudoers.d" in /etc
